### ISSUE TITLE
Cannot install numpy or matplotlib on Pyton 3.12.0.b1

### ISSUE THREAD

**Issue by bersbersbers** [pypa/setuptools#3935]
I am using pip 23.1.2 on Python 3.12.0b1 via pyenv on Windows 10, and I am unable to install matplotlib or numpy:
```
pip install numpy
Collecting numpy
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv\pyenv-win\versions\3.12.0b1\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1216, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I have done the tour via https://github.com/pypa/setuptools/issues/3631 and https://github.com/pypa/pip/issues/11688 all the way to here, which is the only issue still open.

_Originally posted by @bersbersbers in https://github.com/pypa/pip/issues/11501#issuecomment-1562025923_

**Comment by abravalheri** [comment]
Hi @bersbersbers, I think this problem was already solved in [v66.1.0](https://setuptools.pypa.io/en/latest/history.html#v66-1-0).

You can see that the call to `register_finder` is surrounded by an `if hasattr` statement in: https://github.com/pypa/setuptools/blob/b8c0a599676a23048a9041233b423c9dfaf4b70a/pkg_resources/__init__.py#L2230-L2231

Please note that bug fixes in setuptools are published in new versions in a monotonic increasing fashion. Unfortunately we don't have the bandwidth to support older versions or backport bug fixes for old versions.

**Comment by Hoernchen** [comment]
Issue still exists with  Python 3.12.0b4 / pip 23.2.1 / setuptools 68.0.0

**Comment by bersbersbers** [comment]
@Hoernchen that is not surprising considering that https://github.com/numpy/numpy/issues/23808 is still open. You should star that issue.

**Comment by abravalheri** [comment]
Hi @Hoernchen , you sure this does not come with the version of `pkg_resources` that `pip` bundles?

Could you please give a [reproducer](https://stackoverflow.com/help/minimal-reproducible-example) for the issues you are seeing?

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

**Comment by GF-Huang** [comment]
Issue still, I had upgrade all things which need to upgrade.

```
(minerl) F:\Code\minerl>python -V
Python 3.12.2

(minerl) F:\Code\minerl>pip install .
Processing f:\code\minerl
  Preparing metadata (setup.py) ... done
Collecting gym<=0.23.1,>=0.19.0 (from minerl==1.0.2)
  Using cached gym-0.23.1.tar.gz (626 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting opencv-python>=4.1.0.25 (from minerl==1.0.2)
  Using cached opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: setuptools>=49.2.0 in d:\dev\miniconda3\envs\minerl\lib\site-packages (from minerl==1.0.2) (69.2.0)
Collecting tqdm>=4.32.2 (from minerl==1.0.2)
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Collecting numpy<1.24,>=1.16.2 (from minerl==1.0.2)
  Downloading numpy-1.23.5.tar.gz (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "D:\Dev\miniconda3\envs\minerl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Dev\miniconda3\envs\minerl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Dev\miniconda3\envs\minerl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "D:\Dev\miniconda3\envs\minerl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Dev\miniconda3\envs\minerl\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\iFeng\AppData\Local\Temp\pip-build-env-3wi8hs4b\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\iFeng\AppData\Local\Temp\pip-build-env-3wi8hs4b\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\iFeng\AppData\Local\Temp\pip-build-env-3wi8hs4b\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(minerl) F:\Code\minerl>pip install setuptools
Requirement already satisfied: setuptools in d:\dev\miniconda3\envs\minerl\lib\site-packages (69.2.0)

(minerl) F:\Code\minerl>pip install setuptools -U
Requirement already satisfied: setuptools in d:\dev\miniconda3\envs\minerl\lib\site-packages (69.2.0)

(minerl) F:\Code\minerl>pip install --upgrade setuptools
Requirement already satisfied: setuptools in d:\dev\miniconda3\envs\minerl\lib\site-packages (69.2.0)

(minerl) F:\Code\minerl>python -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in d:\dev\miniconda3\envs\minerl\lib\site-packages (69.2.0)

(minerl) F:\Code\minerl>conda list setuptools
# packages in environment at D:\Dev\miniconda3\envs\minerl:
#
# Name                    Version                   Build  Channel
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge

(minerl) F:\Code\minerl>conda upgrade setuptools
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


(minerl) F:\Code\minerl>python -m ensurepip --upgrade
Looking in links: c:\Users\iFeng\AppData\Local\Temp\tmpo78fro0j
Requirement already satisfied: pip in d:\dev\miniconda3\envs\minerl\lib\site-packages (24.0)

(minerl) F:\Code\minerl>
```

**Comment by JhennerTigreros** [comment]
Issue still, I had upgrade all things. I'm trying to install NeMo ToolSuite from [NVIDIA](https://github.com/NVIDIA/NeMo) and get the same output as others

```
?>  pip install 'nemo_toolkit[asr]'
Collecting nemo_toolkit[asr]
  Using cached nemo_toolkit-1.23.0-py3-none-any.whl.metadata (18 kB)
Collecting huggingface-hub (from nemo_toolkit[asr])
  Using cached huggingface_hub-0.22.2-py3-none-any.whl.metadata (12 kB)
Collecting numba (from nemo_toolkit[asr])
  Using cached numba-0.59.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting numpy>=1.22 (from nemo_toolkit[asr])
  Using cached numpy-1.26.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (61 kB)
Collecting onnx>=1.7.0 (from nemo_toolkit[asr])
  Using cached onnx-1.16.0-cp312-cp312-macosx_10_15_universal2.whl.metadata (16 kB)
Collecting python-dateutil (from nemo_toolkit[asr])
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting ruamel.yaml (from nemo_toolkit[asr])
  Using cached ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting scikit-learn (from nemo_toolkit[asr])
  Using cached scikit_learn-1.4.2-cp312-cp312-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: setuptools>=65.5.1 in /Users/jt/Documents/Personal/Code/MVP - Nexo/env/lib/python3.12/site-packages (from nemo_toolkit[asr]) (69.5.1)
Collecting tensorboard (from nemo_toolkit[asr])
  Using cached tensorboard-2.16.2-py3-none-any.whl.metadata (1.6 kB)
Collecting text-unidecode (from nemo_toolkit[asr])
  Using cached text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting torch (from nemo_toolkit[asr])
  Using cached torch-2.2.2-cp312-none-macosx_11_0_arm64.whl.metadata (25 kB)
Collecting tqdm>=4.41.0 (from nemo_toolkit[asr])
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
INFO: pip is looking at multiple versions of nemo-toolkit[asr] to determine which version is compatible with other requirements. This could take a while.
Collecting nemo_toolkit[asr]
  Using cached nemo_toolkit-1.22.0-py3-none-any.whl.metadata (15 kB)
Collecting numpy<1.24,>=1.22 (from nemo_toolkit[asr])
  Using cached numpy-1.23.5.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/jt/Documents/Personal/Code/MVP - Nexo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jt/Documents/Personal/Code/MVP - Nexo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jt/Documents/Personal/Code/MVP - Nexo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/jt/Documents/Personal/Code/MVP - Nexo/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/9_/z28g2c65053gzw82gs_x84h40000gn/T/pip-build-env-exnsie1a/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/9_/z28g2c65053gzw82gs_x84h40000gn/T/pip-build-env-exnsie1a/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/9_/z28g2c65053gzw82gs_x84h40000gn/T/pip-build-env-exnsie1a/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by abravalheri** [comment]
Please have a lookbon the previous comments.

This is likely an issue with how old versions of numpy cap `setuptools` versions range to older versions that don't work on Python 3.12.

You likely need a newer version of numpy.

See the numpy issue mentioned above.
