### ISSUE TITLE
[BUG] setuptools 69.4.0 breaks mpi4py installation

### ISSUE THREAD

**Issue by dalcinl** [pypa/setuptools#4303]
### setuptools version

69.4.0

### Python version

all

### OS

POSIX

### Description

Originally reported at https://github.com/mpi4py/mpi4py/issues/484

The commit https://github.com/pypa/setuptools/commit/a131f83e2967514e2973fb36f2ca64e3ac8efc3c changed the return type of a publich method within a public class within a public module.

### Expected behavior

`pip install mpi4py` should succeed with no traceback.

### How to Reproduce

`pip install mpi4py` should be enough.

However, it cannot be reproduced easily as setuptools 69.4.0 was yanked for other reasons.

### Output

```console
File "/tmp/pip-build-env-qxqtzla9/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1232, in gen_lib_options
          lib_opts.extend(always_iterable(compiler.runtime_library_dir_option(dir)))
        File "/tmp/pip-install-u2viu3lx/mpi4py_70e5ecd7d41d4c9fb50ac4e92d5eb59f/conf/mpidistutils.py", line 68, in rpath_option
          if option.startswith('-R'):
      AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by dalcinl** [comment]
Looks like the method causing the issue was always allowed to return either `str` or `list[str]`, and setuptools just made use use of such freedom relatively recently changing from `str` to `list[str]`.

Is there any change setuptools would accept the following:

```python
return [
    # Force RUNPATH instead of RPATH
    "-Wl,--enable-new-dtags",
    "-Wl,-rpath," + dir
]
```

to this?

```python
# Force RUNPATH instead of RPATH
return "-Wl,--enable-new-dtags,-rpath," + dir
```

**Comment by jaraco** [comment]
That change was introduced in https://github.com/pypa/distutils/pull/214 by @haampie with this rationale:

> Also split `-Wl,--enable-new-dtags` and `-Wl,-rpath,...` into two separate arguments, which is more common, and more likely to be parsed correctly by compiler wrappers.

Whatever the fix is, it'll need to be contributed to distutils first and then merged here (changes directly to _distutils aren't allowed), but that can be done relatively easily and quickly. I'm transferring the issue there.
