### ISSUE TITLE
[BUG] rmtree() got an unexpected keyword argument 'onexc' with py312 and editable install

### ISSUE THREAD

**Issue by ssbarnea** [pypa/setuptools#4882]
### setuptools version

setuptools>75.3.2 # 75.3.2 works but all versions greater than this fail with py312 in particular when trying to perform editable installs (work fine with 3.10, 3.11 or 3.13).

### Python version

3.12

### OS

macos

### Description

Apparently on python 3.12 there is a some code that is broken in all recent versions of setuptools when trying to perform editable installs.

Apparently today's release of 75.3.2 works, but sadly there are many other releases with greater numbers that are all broken (tested all).

I guess that the fix from 75.3.2 should be released soon, so we can add a proper condition to setuptools version needed for packaging.

### Expected behavior

Build and install package.

### How to Reproduce

-

### Output

```console
❯ tox -e py312
ROOT: will run in automatically provisioned tox, host /Users/ssbarnea/.venv/bin/python3 is missing [requires (has)]: tox-extra>=2.0.2, tox-uv>=1.20.2
ROOT: provision> .tox/.tox/bin/python -m tox -e py312
.pkg-cpython312: recreate env because dependencies removed: setuptools==75.8.2
.pkg-cpython312: remove tox env folder /Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312
.pkg-cpython312: venv> .tox/.tox/bin/uv venv -p cpython3.12 --allow-existing --python-preference system /Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312
.pkg-cpython312: install_requires> .tox/.tox/bin/uv pip install setuptools==75.4.0 'setuptools_scm[toml]>=7.0.5'
.pkg-cpython312: _optional_hooks> python /Users/ssbarnea/code/a/pytest-ansible/.tox/.tox/lib/python3.13/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg-cpython312: get_requires_for_build_editable> python /Users/ssbarnea/code/a/pytest-ansible/.tox/.tox/lib/python3.13/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg-cpython312: build_editable> python /Users/ssbarnea/code/a/pytest-ansible/.tox/.tox/lib/python3.13/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py312: packaging backend failed (code=1), with TypeError: rmtree() got an unexpected keyword argument 'onexc'
Traceback (most recent call last):
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 132, in run
    self._ensure_dist_info()
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 151, in _ensure_dist_info
    dist_info.run()
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 103, in run
    bdist_wheel.egg2dist(egg_info_dir, self.dist_info_dir)
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 613, in egg2dist
    adios(egginfo_path)
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 550, in adios
    _shutil.rmtree(p)
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/_shutil.py", line 48, in rmtree
    return py311.shutil_rmtree(path, ignore_errors, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/compat/py311.py", line 21, in shutil_rmtree
    return shutil.rmtree(path, ignore_errors, onexc=onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: rmtree() got an unexpected keyword argument 'onexc'
/Users/ssbarnea/code/a/pytest-ansible/.tox/.pkg-cpython312/lib/python3.12/site-packages/setuptools/_distutils/dist.py:973: _DebuggingTips: Problem in editable installation.
!!

        ********************************************************************************
        An error happened while installing `pytest-ansible` in editable mode.

        The following steps are recommended to help debug this problem:

        - Try to install the project normally, without using the editable mode.
          Does the error still persist?
          (If it does, try fixing the problem before attempting the editable mode).
        - If you are using binary extensions, make sure you have all OS-level
          dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
        - Try the latest version of setuptools (maybe the error was already fixed).
        - If you (or your project dependencies) are using any setuptools extension
          or customization, make sure they support the editable mode.

        After following the steps above, if the problem still persists and
        you think this is related to how setuptools handles editable installations,
        please submit a reproducible example
        (see https://stackoverflow.com/help/minimal-reproducible-example) to:

            https://github.com/pypa/setuptools/issues

        See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
        ********************************************************************************

!!
  cmd_obj.run()
```

**Comment by ssbarnea** [comment]
Apparently this issue was caused by something quite different: tox was picking the system python3.13 on my macos 15.3.1 machine which has an unexpected version:

```
/usr/local/bin/python3 --version
Python 3.12.0a4
```

Not sure how this happened but this version would not work with setuptools, release versions do work, so this bug is basically related to the version constraint. What is even more curious is how this version got installed... as I probably never used it.

**Comment by abravalheri** [comment]
According to the [Python docs](https://docs.python.org/3/library/shutil.html#shutil.rmtree) `rmtree` accepts `onexc` starting from 3.12.

Could you please ensure you use a stable version?
