### PR TITLE
Workaround for `bdist_wheel.dist_info_dir` problems

### LINKED ISSUE #4683: `bdist_wheel.dist_info_dir` seems to have broken building some projects (e.g. pyyaml).
This seems to have broken building some projects.  https://github.com/yaml/pyyaml I am seeing failures like:

```
Processing /home/tcaswell/source/p/yaml/pyyaml
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: PyYAML
  Building wheel for PyYAML (pyproject.toml): started
  Building wheel for PyYAML (pyproject.toml): finished with status 'error'
Failed to build PyYAML

  error: subprocess-exited-with-error

  × Building wheel for PyYAML (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: _in_process.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: _in_process.py --help [cmd1 cmd2 ...]
         or: _in_process.py --help-commands
         or: _in_process.py cmd --help

      error: option --dist-info-dir not recognized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyYAML
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyYAML)
```

with the main branch of setuptools, but going back to the commit before this was merged (3106af0512fe67464a8b5e7524c07fddf7717660 which is v75.1.0) works again. 

I have not had time to debug this further and it is not _all_ packages nor do I know if this is the only one.

_Originally posted by @tacaswell in https://github.com/pypa/setuptools/issues/4647#issuecomment-2395672359_

### PR DESCRIPTION
**Pull request by abravalheri**
## Summary of changes

This is a workaround identified in https://github.com/pypa/setuptools/pull/4647#issuecomment-2395672359

We should be able to see the integration tests failing or passing for PyYAML in https://github.com/pypa/setuptools/actions/runs/11353165220

Closes #4683 

### Pull Request Checklist
- [ ] Changes have tests
- [x] News fragment added in [`newsfragments/`].
  _(See [documentation][PR docs] for details)_

[`newsfragments/`]: https://github.com/pypa/setuptools/tree/master/newsfragments
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by abravalheri** [comment]
Seems to work as per https://github.com/pypa/setuptools/actions/runs/11353165220/job/31578117635.

**Comment by abravalheri** [comment]
@pelson could you please have a look?

The objective is to avoid breaking old packages in the ecosystem that have not updated yet.

**Comment by pelson** [comment]
First impression: complex but reasonable. Thanks for tidying this up :+1:.

I have to say that in general perhaps a more defensive infrastructure is needed around the command concept, otherwise we can never extend the capabilities of a particular command without breaking something for somebody who implemented an alternative command of the same name.

**Comment by abravalheri** [comment]
> First impression: complex but reasonable. Thanks for tidying this up 👍.

Yeah, I tried adding the exception handling in at least 3 other places before landing on this approach, which I thing was the best between all the ones I tried...

> I have to say that in general perhaps a more defensive infrastructure is needed around the command concept, otherwise we can never extend the capabilities of a particular command without breaking something for somebody who implemented an alternative command of the same name.

Agreed. Do you have any suggestion for that?

**Comment by abravalheri** [comment]
I will go ahead and merge this now so that we can cut a release.

We can revisit the implementation and make it simpler in a follow up if anyone has a better idea.

**Comment by bebound** [comment]
Our pipeline suddenly fails after Oct 16, after 75.2.0 is released. I'm not sure if it is related to this PR.

I can only repro the error on macOS.

Please ignore `TypeError: print() got an unexpected keyword argument 'color'`. `getopt.GetoptError: option --dist-info-dir not recognized` seems to be related?

Updating to a newer version can fix it, but I'm curious why this error occurs.

```
pip install psutil==5.9.5 --no-binary :all:                                                                                                     

Collecting psutil==5.9.5
  Using cached psutil-5.9.5.tar.gz (493 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/fancy_getopt.py", line 245, in getopt
          opts, args = getopt.getopt(args, short_opts, self.long_opts)
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/getopt.py", line 93, in getopt
          opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
                       ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/getopt.py", line 157, in do_longs
          has_arg, opt = long_has_args(opt, longopts)
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/getopt.py", line 174, in long_has_args
          raise GetoptError(_('option --%s not recognized') % opt, opt)
      getopt.GetoptError: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 170, in setup
          ok = dist.parse_command_line()
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 472, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 893, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 576, in _parse_command_opts
          (args, opts) = parser.getopt(args[1:])
                         ~~~~~~~~~~~~~^^^^^^^^^^
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/fancy_getopt.py", line 247, in getopt
          raise DistutilsArgError(msg)
      distutils.errors.DistutilsArgError: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 462, in main
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 172, in setup
          raise SystemExit(gen_usage(dist.script_name) + f"\nerror: {msg}")
      SystemExit: usage: _in_process.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: _in_process.py --help [cmd1 cmd2 ...]
         or: _in_process.py --help-commands
         or: _in_process.py cmd --help

      error: option --dist-info-dir not recognized

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/kk/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/kk/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kk/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', metadata_directory])
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 422, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/mg/sgkthmt12jn_gq4ymlyb_pcw0000gn/T/pip-build-env-uq16auuo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 497, in <module>
        File "<string>", line 480, in main
      TypeError: print() got an unexpected keyword argument 'color'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psutil)
```

**Comment by abravalheri** [comment]
Hi @bebound, this seems to be a different problem.

The `getopt.GetoptError: option --dist-info-dir not recognized` i


`TypeError: print() got an unexpected keyword argument 'color'` is transformed by `distutils` to `distutils.errors.DistutilsArgError` and in turn into a `SystemExit`, which as per this PR, `setuptools` is well equipped to handle.

Now the other error that seems to be the root case of the problem is `TypeError: print() got an unexpected keyword argument 'color'`, and that seems to come from the `setup.py` script of the package in question. Could you please have a look on that? If it persists please open an issue with a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by pelson** [comment]
> setuptools is well equipped to handle

:+1: - thanks again. The backwards compatibility of projects who used to import wheel in their `setup.py` was not something I had foreseen in my PR.

> Now the other error that seems to be the root case of the problem is `TypeError: print() got an unexpected keyword argument 'color'`, and that seems to come from the `setup.py` script of the package in question. Could you please have a look on that? If it persists please open an issue with a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example).

The psutil 5.x versions imported wheel in their `setup.py`. 
https://github.com/giampaolo/psutil/blob/27a1432daeacd46b287517c11bfea2af4fd95a88/setup.py#L37

The error for `release-5.9.5` was seemingly fixed in https://github.com/giampaolo/psutil/commit/6e23a5129375ae19abadc0de49f920899b6e765c#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R505 (`5.9.6`), and isn't an issue with `setuptools` at all.

**Comment by bebound** [comment]
Thanks for the response.

`TypeError: print() got an unexpected keyword argument 'color'` is caused by a wrong misplaced parenthesis in `setup.py`. （`color="red"` should be part of `hilite`） It's not related to setuptools.
https://github.com/giampaolo/psutil/blob/0d4900b073f8697ab21c47d823621bea61f39a3b/setup.py#L480-L481
``` python
            elif MACOS:
                print(hilite("XCode (https://developer.apple.com/xcode/) "
                             "is not installed"), color="red", file=sys.stderr)
```
---------

I'm still confused.

In 75.1.0, if I have `from wheel.bdist_wheel import bdist_wheel` in `setup.py`, then `getopt.GetoptError: option --dist-info-dir not recognized` will be raised.

In 75.2.0, this PR tries to suppress the `SystemExit` converted from `getopt.GetoptError`.

However, for `psutil==5.9.5`, it works in 75.1.0, but fails in 75.2.0, which is completely reversed?

**Comment by abravalheri** [comment]
As codebase naturally changes, this kind of stuff is normal.

This PR in setuptools does not only "supress" the error. It identifies an anomally (usage of a deprecated functionality from `wheel` by the package being built) and adds the appropriate workaround.

The package tries to wrap the call to `try...finally` and introduces an argument error. That is what made prone to error.

The advice for package developers that want long-term support from setuptools is:

1. Keep an eye on deprecations and try to address them as soon as possible.
2. Avoid creating brittle `setup.py` scripts and don't assume that the `setup.py` is going to be the outer most Python frame executed (that view is incompatible with PEP 517).
