### ISSUE TITLE
setuptools 50.0 MSVC: CCompiler_spawn() got an unexpected keyword argument 'env'

### ISSUE THREAD

**Issue by mbeyeler** [pypa/setuptools#2368]
After upgrading to setuptools 50.0, my Cython-based package extensions no longer build. The 'env' in `return super().spawn(cmd, env=env)` seems to be the problem.

```
self.run_command('build_ext')
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\command\build_ext.py", line 274, in run
    self.build_extensions()
  File "D:\a\1\s\setup.py", line 168, in build_extensions
    if self.can_compile_link(compile_flags, link_flags):
  File "D:\a\1\s\setup.py", line 142, in can_compile_link
    extra_postargs=compile_flags)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 403, in compile
    self.spawn(args)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 507, in spawn
    return super().spawn(cmd, env=env)
  File "c:\cibw\python\pythonx86.3.5.4\tools\lib\site-packages\numpy\distutils\ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

Downgrading to setuptools 49.6 fixes the issue. Using `numpy-1.18.5-cp35-cp35m-win_amd64.whl`.

Thanks,
Michael

**Comment by jaraco** [comment]
It looks like the issue is that numpy is incompatible with the changes in pypa/distutils#6. Please file a bug with numpy to address the issue. Thanks.

**Comment by jaraco** [comment]
The other workaround is to set `SETUPTOOLS_USE_DISTUTILS=stdlib` in the environment when running the build (disabling the use of Setuptools' local copy of distutils).

**Comment by sverzakov** [comment]
I am not sure that the problem should be solved on numpy side. At least not in the case of mbeyeler:

mbeyeler uses Python 3.5.4, distools of which do not contain your changes of July 12 (env parameter of spawn). So numpy is (most probably) compatible with the installed distools, but setuptools >49.1.2 are not compatible with distools of Python 3.5.4. 

This will be the case not only for the "ancient" release 3.5.4, but for all Python releases made before July 12 or even after that:  distools of Python releases 3.7.9 and 3.8.5 also do not contain spawn() with env parameter. I wonder if 3.9 has it?

So, maybe, "monkey patching" still should be done for Python < 3.9?

**Comment by jaraco** [comment]
Python 3.9 does not have that change. The change was only applied to pypa/distutils and has only been released as part of the setuptools distutils adoption (#417).

What I'm hoping is that numpy can add support for this new version of distutils that supports this new interface.

**Comment by sverzakov** [comment]
The problem is that even if numpy add support of spawn() with env param it will not solve all the issues. As explained in [#17209 (comment)](https://github.com/numpy/numpy/pull/17209#issuecomment-685181604), "scikit-learn needs to build with NumPy 1.13.3 right now", so not only all active minor versions of numpy should be re-released, but scikit-learn should be re-released too.

I think it boils down to a question which interface / semantics numpy must follow: the one of the stdlid  distutils or the one of setuptools.distutils. There is no easy answer to it, because on one hand, numpy patches distutils.ccompiler and thus is expected to follow signatures of stdlib distutils and may expect that patches applied before it also do that. On the other hand, numpy is aware of setuptools and uses them, although in an optional way, so there is a dependency on setuptools and then setuptools should expect that their users comply to setuptools signatures and semantics.

Do you know if spawn() with env param will be added into the stdlib distutils of Python 3.10 or later?

**Comment by rgommers** [comment]
Short-term, this problem should be worked around by pinning to `setuptools <50.0` or using `SETUPTOOLS_USE_DISTUTILS="stdlib". 

For the longer-term solution to this and other `numpy.distutils` related issues, I have opened gh-2372.

**Comment by riedgar-ms** [comment]
We seem to have hit this issue as well - `pip install` of our requirements fails with:
```
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```
This only happens for Python 3.8 on Windows when we pin `numpy`, `scipy` etc. to the lowest version we claim to support. Things work fine on Linux and MacOS, and also for the other Python versions on Windows (we test 3.6 and 3.7 as well). We only pin our direct dependencies, though - not a full `pip freeze`.

I'm going to try putting in that upper bound on `setuptools` as a work around.

**Comment by sverzakov** [comment]
I had such a problem on Python 3.7 (solved it by downgrading setuptools to 49.1.2, I do not think just <50.0 is low enough). Python version should not make any difference, unless you do different things for different versions yourself. Maybe for 3.6 and 3.7 versions you have cached pre-built wheels? Try to clean the pip cache up..

As to OS: it seems that param env is used only for MS VC compiler, so it figures, unless I'm very much mistaken.

**Comment by rgommers** [comment]
> I had such a problem on Python 3.7 (solved it by downgrading setuptools to 49.1.2, I do not think just <50.0 is low enough)

This may be the case; there's multiple issues right now that you may or may not be hitting. NumPy itself is pinned to `<49.2.0` on all platforms, SciPy to `<50.0` in its Windows CI.

**Comment by riedgar-ms** [comment]
And that failed as well. But still, only on Python 3.8 on Windows. Python 3.6 and 3.7 on Windows work.

I'm not sure if I'm reading the logs correctly, but things like:
```
Found executable C:\ProgramData\Chocolatey\bin\gfortran.exe
    Using built-in specs.
    COLLECT_GCC=C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\gfortran.exe
    COLLECT_LTO_WRAPPER=C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/8.1.0/lto-wrapper.exe
    Target: x86_64-w64-mingw32
    Configured with: ../../../src/gcc-8.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/include -I/c/mingw810/prerequisites/x86_64-zlib-static/include -I/c/mingw810/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/x86_64-810-posix-seh-rt_v6-rev0/mingw64/opt/lib -L/c/mingw810/prerequisites/x86_64-zlib-static/lib -L/c/mingw810/prerequisites/x86_64-w64-mingw32-static/lib '
    Thread model: posix
    gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
      NOT AVAILABLE
```
make me wonder if it's also trying to use gcc (via MinGW).

**Comment by rgommers** [comment]
@riedgar-ms MinGW + gfortran sounds like an unrelated problem to the `CCompiler.spawn` that this issue is for. You may want to keep it on your own repo, or if you see that it's related to `numpy.distutils`, report on the NumPy issue tracker.

**Comment by jaraco** [comment]
> Do you know if spawn() with env param will be added into the stdlib distutils of Python 3.10 or later?

That's uncertain. The plan is to deprecate stdlib distutils and direct users/systems to migrate to Setuptools instead. I think it's a small likelihood the change will be ported to CPython 3.10.

I acknowledge that this incompatibility is unanticipated so probably deserves some consideration. I believe distutils could be augmented with a shim to provide backward compatibility. That is, if the call to spawn fails with a TypeError, patch os.environ and retry without the env (possibly utilizing a lock to prevent the race condition).

Would that work?

**Comment by rgommers** [comment]
Thanks, that sounds like a good band aid to me, should work. I'd be happy to test the patch on SciPy Windows CI if needed.

**Comment by riedgar-ms** [comment]
> @riedgar-ms MinGW + gfortran sounds like an unrelated problem to the `CCompiler.spawn` that this issue is for. You may want to keep it on your own repo, or if you see that it's related to `numpy.distutils`, report on the NumPy issue tracker.

We definitely had the symptom `TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'` as well, but I'll see about reporting the Fortran issue on Numpy.

**Comment by riedgar-ms** [comment]
Tracked it down. I had forgotten another stage before the main `pip install` which updated `setuptools`. Running combinations of

- Linux or Windows
- Python 3.6, 3.7, 3.8
- Updating or not `setuptools`
- Installing `numpy==1.17.2` or `numpy>=1.17.2`

The only consistently failing combination is:

- Windows
- Python 3.8
- Updating `setuptools`
- Install `numpy==1.17.2`

All other combinations pass.
