### ISSUE TITLE
Cannot import name "Feature" from "setuptools" in version 46.0.0

### ISSUE THREAD

**Issue by pantunes** [pypa/setuptools#2017]
Your last version is giving the following error:

`ImportError: cannot import name 'Feature' from 'setuptools'`

**Comment by cristianozhang** [comment]
I got same issue

**Comment by pganssle** [comment]
This appears to be a deprecated API that was first removed in version 3.0 (41 major versions ago). Not sure why it was put back, but it was deprecated in issue #65 and most recently removed in #1979 .

If it causes problems for you I think pinning to setuptools < 46 while you find another solution is the right way to go.

**Comment by pganssle** [comment]
Closing this as it was an intended change. Thank you for reporting this!

**Comment by dwilhel1** [comment]
>pinning to setuptools < 46 while you find another solution is the right way to go.

I'm a little new to Python-related utils and such, here's the command I had to use to resolve this: `pip3 install setuptools==45`

**Comment by levsa** [comment]
I don't understand this error, why is `setuptools/__init__.py` still importing `Feature` if it is removed? Because I see the error there (in a docker build based on python3.7-stretch):

```
ImportError: cannot import name 'Feature' from 'setupt...r/local/lib/python3.7/site-packages/setuptools/__init__.py
```

**Comment by gkulkarni21** [comment]
> > pinning to setuptools < 46 while you find another solution is the right way to go.
> 
> I'm a little new to Python-related utils and such, here's the command I had to use to resolve this: `pip3 install setuptools==45`

I tried this but still getting error saying: ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.7/site-packages/setuptools/__init__.py)

**Comment by gkulkarni21** [comment]
> > > pinning to setuptools < 46 while you find another solution is the right way to go.
> > 
> > 
> > I'm a little new to Python-related utils and such, here's the command I had to use to resolve this: `pip3 install setuptools==45`
> 
> I tried this but still getting error saying: ImportError: cannot import name 'Feature' from 'setuptools' (/usr/local/lib/python3.7/site-packages/setuptools/**init**.py)

I was able to overcome this by setting zope.interface version to greater than 5.0.0 in requirements.txt

**Comment by lwalejko** [comment]
I see that it was removed in #65, re-introduced in #161, and removed again in #1979

**Comment by p-mongo** [comment]
So what is the cause of this error and what is the fix?

Pinning `setuptools==45` works but is not a fix for the error.

**Comment by vhquang** [comment]
> So what is the cause of this error and what is the fix?
>Pinning setuptools==45 works but is not a fix for the error.

Paul Ganssle and few other pointed out the original issue, where "Feature" was decided to be removed (and it was 2013). Pinning version of setuptools is just a work around that we can do on our side. The true fix need to come from package maintainer to update their setup script not to use that "Feature".

**Comment by p-mongo** [comment]
Is there documentation that I can point package maintainers to which describes the steps that must be taken by them?

**Comment by vhquang** [comment]
I am not aware of any such documentation, but I think you can help pointing them here, or to take a look at other linked issues here for more references. For example, this is the update done by `jaraco` who also handled the deprecation of Feature himself:
https://github.com/pallets/markupsafe/pull/24

**Comment by SwapnilSoni1999** [comment]
Issue is still present

**Comment by dozzman** [comment]
> > pinning to setuptools < 46 while you find another solution is the right way to go.
> 
> I'm a little new to Python-related utils and such, here's the command I had to use to resolve this: `pip3 install setuptools==45`

I believe `pip3 install 'setuptools<46'` is more appropriate.

**Comment by p-mongo** [comment]
So this removal of `Feature` (whatever it actually is/was/was used for) appears to be an incompatible change. I understand that incompatible changes may be made but as a user I expect them to be documented in some way with a description of the change and steps needed to be taken in client code to deal with the change. For this particular change it seems that there isn't any documentation which creates a poor user experience for, it looks like, quite a large number of users.

**Comment by AgentIvan** [comment]
how if use:
`python -m pip install --upgrade pip setuptools wheel`
?

**Comment by rufatpro** [comment]
Fixed when I use Python 3.8 and `pip3 install setuptools==57.4`.

**Comment by rufatpro** [comment]
But it doesn't work on Windows when I use Python 3.9 or Python 3.10 with any version of setuptools.

**Comment by abravalheri** [comment]
Hi @rufatpro, according to https://github.com/pypa/setuptools/issues/2017#issuecomment-596307305, the issue reported here is caused by a deprecated functionality removed long time ago.

Since setuptools does not provide LTS support for old versions, the best action forward is to try updating your dependencies and/or inform the maintainers of third party libraries if they are still relying on `Features`, as indicated in https://github.com/pypa/setuptools/issues/2017#issuecomment-662591685.
