### ISSUE TITLE
[BUG] 71.0.0 fails with `'importlib_metadata' has no attribute 'EntryPoints'` on Python 3.8

### ISSUE THREAD

**Issue by bmcalary-atlassian** [pypa/setuptools#4478]
### setuptools version

71.0.0

### Python version

3.8

### OS

Ubuntu 20.04

### Description

This started a few hours ago when our pipeline picked up 71.0.0, works fine on 70.3.0. 

```
python3 -m pip install --upgrade --no-cache-dir --no-color --no-input --upgrade pip packaging setuptools python-debian
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (24.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (71.0.0)

python3 -m pip install --no-cache-dir --no-color --no-input https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz --upgrade
Collecting https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
  Downloading https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz (549 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.6/549.6 kB 690.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 19, in <module>
          from .dist import Distribution
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 30, in <module>
          from . import _entry_points
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_entry_points.py", line 44, in <module>
          def validate(eps: metadata.EntryPoints):
      AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
      [end of output]
```

### Expected behavior

No error

### How to Reproduce

See Description

### Output

See Description

**Comment by jaraco** [comment]
This behavior is by design. Setuptools now will prefer installed packages over its vendored ones, but it can't yet declare them. That means that if you have an installed dependency but it's older than the one setuptools needs, it will not work. 

The workaround/fix is to install [these dependencies](https://github.com/pypa/setuptools/blob/f2a6bb190202577595a45ceebdedb0016b7cf864/pyproject.toml#L109-L119) when installing setuptools. You may be tempted to install `setuptools[core]`, but please don't as that's unsupported and will likely break in the future.

Eventually, we plan to have setuptools declare (and thus install) its own dependencies so you don't have to do that, but for Setuptools to do that, we first have to solve https://github.com/pypa/packaging-problems/issues/342 (an ongoing effort).

**Comment by bmcalary-atlassian** [comment]
Thanks, importing those, specifically importlib_metadata fixed the problem.
