### ISSUE TITLE
Problem with setuptools using zc.buildout

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#508]
Originally reported by: **tiagofrepereira (Bitbucket: [tiagofrepereira](http://bitbucket.org/tiagofrepereira), GitHub: [tiagofrepereira](http://github.com/tiagofrepereira))**

---

When I try to run the boostrap-buildout script I got the following error from  setuptools (with the setuptools at least one version behind the current)

```
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.2.2.zip
Extracting in /tmp/tmpCG9_5t
Now working in /tmp/tmpCG9_5t/setuptools-20.2.2
Building a Setuptools egg in /tmp/bootstrap-b6t61T
warning: no files found matching '*.py' under directory '_markerlib'
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-b6t61T/setuptools-20.2.2-py2.7.egg
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 117, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 132, in _do_download
  File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/setuptools/extern/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 48, in <module>
  File "/local/scratch/tpereira/virtual_envs/py27/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    mod = sys.modules[extant]
AttributeError: 'NoneType' object has no attribute 'modules'
```

Follow below the steps to reproduce the problem.

```
virtualenv -p /usr/bin/python2.7 py27
./bin/pip install --upgrade setuptools==20.0
wget https://bootstrap.pypa.io/bootstrap-buildout.py
/<VIRTUAL_ENV>/bin python bootstrap-buildout.py
```

If you pin the setuptools with the same version that you have in your virtualenv (20.0 in our example), I have no error, but obviously this is not a clean solution.

Debugging a bit I found that when the setuptools try to load the module `six` (pkg_resources.extern.six) the `sys` module is None for some reason.
The module is imported in the beginning of the script (https://bitbucket.org/pypa/setuptools/src/6a15a32d0dabd7408556fe39bc5d9027f24b552e/pkg_resources/extern/__init__.py?at=default&fileviewer=file-view-default).

Thanks for looking at it.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/508

**Comment by abravalheri** [comment]
Since `ez_setup` is deprecated and both linked issues have been resolved (the first one indicates that users should use `virtualenv` and the second one indicates that a more recent version of setuptools solves the problem), I think we can close this ticket for now.

If anyone is still having problems, please feel free to comment bellow or open a new issue.

Thank you very much for the users that added debugging information!
