### ISSUE TITLE
[BUG] unable to build package on python 3.10.0 with declarative config

### ISSUE THREAD

**Issue by adigitoleo** [pypa/setuptools#3546]
### setuptools version

setuptools>=52.0.0

### Python version

Python 3.10.0a6

### OS

Ubuntu

### Additional environment information

Output of `lsb_release -a`:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

I'm not able to move to Ubuntu 22 right now. Because this system is ~~a dinosaur~~ still on Python 2.7 by default, I use [pyenv](https://github.com/pyenv/pyenv) to manage Python versions.

Output of `pyenv versions`:

```
  system
* 3.10.0a6 (set by /home/leon/.pyenv/version)
```

I set up a virtual environment with:

```
$(pyenv prefix)/bin/python3 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip flake8 mypy black
```

### Description

I'm unable to build/install a package in the above indicated environment. Upgrading the setuptools version doesn't help. Upgrading `importlib_metadata` doesn't help.

### Expected behavior

I use pyenv to set my Python version to 3.10, then create the virtual environment. Then I try to install the package with either of:

```
pip install .
pip install -e .
```

It don't work.

### How to Reproduce

I tried with a minimal package and can reproduce the issue. Output of `tree`:

```
.
├── pyproject.toml
├── setup.cfg
├── setup.py
└── src
    └── python_setuptools_bug
        ├── core.py
        └── __init__.py
```

My `pyproject.toml`:
```
# Boilerplate for modern (PEP517, PEP518) build systems.
# The setup.cfg metadata may eventually migrate over here, see:
# https://github.com/pypa/setuptools/issues/1688
# https://www.python.org/dev/peps/pep-0621/
# https://snarky.ca/what-the-heck-is-pyproject-toml/
[build-system]
requires = ["setuptools >= 42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

# Automatically use the version number from vcs (e.g. git) tags,
# <https://github.com/pypa/setuptools_scm>.
[tool.setuptools_scm]
```

My `setup.cfg`:
```
# Packaging configuration and metadata.
# <https://packaging.python.org/en/latest/tutorials/packaging-projects/>
# <https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html>
# <https://docs.python.org/3/distutils/configfile.html>
[metadata]
name = python_setuptools_bug
description = Reproducer for python setuptools bug

[options]
# YES, IT NEEDS THE SECOND '=', <https://github.com/pypa/setuptools/issues/1259>.
package_dir =
    = src
# Find all the *.py files in options.packages.find["where"] (recursive).
packages = find:

# Required for src/ setup.
[options.packages.find]
where = src
```

My `setup.py`:
```
"""Setuptools shim for pre-PEP571 build methods."""
import setuptools  # type: ignore

# DO NOT EDIT, use setup.cfg instead.
if __name__ == "__main__":
    setuptools.setup()
```

Contents of `src/python_setuptools_bug/core.py` is arbitrary, I have put:
```
def main():
    print("I'm a bug. 🐛")
```

### Output

```console
Processing /home/leon/srcbuilds/python_setuptools_bug
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/leon/srcbuilds/python_setuptools_bug/.venv-python_setuptools_bug/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/leon/srcbuilds/python_setuptools_bug/.venv-python_setuptools_bug/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/leon/srcbuilds/python_setuptools_bug/.venv-python_setuptools_bug/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 57, in __init__
          super().__init__(filtered)
        File "/tmp/pip-build-env-xwiy0fou/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 474, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
      TypeError: entry_points() got an unexpected keyword argument 'group'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by adigitoleo** [comment]
Can confirm that upgrading Python to 3.10.6 fixes the issue, which is good enough for me. I guess these early 3.10 versions might still be a problem for people though.

**Comment by abravalheri** [comment]
Hi @adigitoleo, thank you very much for reporting this.

I tested your reproduction in the `python:3.10.0` docker container, without experiencing any problems/errors.

I understand that you have initially tested this with an alpha version of Python 3.10. Since alpha versions are kind of expected to misbehave, I think it would be OK if we close this issue.

Please let us know if you (or anyone) still experience the same issue in a stable Python release.

**Comment by adigitoleo** [comment]
> I understand that you have initially tested this with an alpha version of Python 3.10.0

Ah that's true, I just tested on 3.10.0 proper as well but I still hit the same error. However, if it works in docker then maybe my pyenv setup or something about my environment is to blame.

**Comment by abravalheri** [comment]
There is a possibility.

The original error shows the following message:

```
TypeError: entry_points() got an unexpected keyword argument 'group
'```

Runtime evidence that `group=` works in Python 3.10.0 is given by the example with the `python:3.10.0` container. Documentation evidence is given by the [method docstring](https://github.com/python/cpython/blob/b494f5935c92951e75597bfe1c8b1f3112fec270/Lib/importlib/metadata/__init__.py#L949-L971) 
in the source code for Python 3.10.0, which mentions the possibility of using `name` or `group` argument.

> Return EntryPoint objects for all installed packages. Pass selection parameters (group or name) to filter the result to entry points matching those properties (see EntryPoints.select()).

There is also a [example in the Python documentation for 3.10.0](https://github.com/python/cpython/blob/v3.10.0/Doc/library/importlib.metadata.rst#entry-points) explicitly showing the usage of `entry_points(groups=...)`:

```python
>>> scripts = entry_points(group='console_scripts')  # doctest: +SKIP
```

We can investigate this issue further, but for that we would need a minimal reproducer (that does not involve pyenv).

**Comment by abravalheri** [comment]
For reference, this is the reproducer with Python 3.10.0:

```bash
# docker run --rm -it python:3.10.0 bash

apt update && apt install -y git
rm -rf /tmp/proj_root && mkdir -p /tmp/proj_root

cat <<EOF > /tmp/proj_root/pyproject.toml
[build-system]
requires = ["setuptools >= 42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
EOF

cat <<EOF > /tmp/proj_root/setup.cfg
[metadata]
name = python_setuptools_bug
description = Reproducer for python setuptools bug

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src
EOF

cat <<EOF > /tmp/proj_root/setup.py
import setuptools
if __name__ == "__main__":
    setuptools.setup()
EOF

mkdir -p /tmp/proj_root/src/python_setuptools_bug/
touch /tmp/proj_root/src/python_setuptools_bug/__init__.py
cat <<EOF > /tmp/proj_root/src/python_setuptools_bug/core.py
def main():
    print("I'm a bug. 🐛")
EOF

python -m venv /tmp/venv
cd /tmp/proj_root
git config --global init.defaultBranch main
git init .
/tmp/venv/bin/python -m pip install -U pip
/tmp/venv/bin/python -m pip install -e .
# ...
# Successfully installed python-setuptools-bug-0.1.dev0
cd /var
/tmp/venv/bin/python -c 'import python_setuptools_bug.core as m; m.main()'
# I'm a bug. 🐛
python -V
# Python 3.10.0
/tmp/venv/bin/python -V
# Python 3.10.0
```

Everything seems to work.
