### ISSUE TITLE
[BUG] setuptools 71.0.3 vendored typeguard crash on Python 3.8: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by marcinsulikowski** [pypa/setuptools#4499]
### setuptools version

 71.0.3

### Python version

3.8

### OS

Linux (Ubuntu 20.04)

### Description

The latest setuptools is still not working correctly on Python 3.8. In my case it crashes on Pytest initialization – see more information below.

It just used to work just fine two days ago with setuptools 70.3.0. It stopped working after the release 71.0.1 but that was yanked quickly. Unfortunately something is still not right in 71.0.3

### Expected behavior

It just used to work just fine two days ago with setuptools 70.3.0.

### How to Reproduce

I do not have exact or minimal reproduction steps yet but maybe the stacktace alone is sufficient for you to tell what the problem is. What I am doing is basically:
* Use `get-pip.py` with on Python 3.8 (Ubuntu 20.04) to get `pip`. That also installs the latest setuptools.
* Install `pytest` and a bunch of other dependencies needed to run tests in my project.
* Call `pytest`

### Output

`get-pip.py`:
```console
Installing pip in /tmp/venv...
Collecting pip
  Downloading pip-24.1.2-py3-none-any.whl.metadata (3.6 kB)
Collecting setuptools
  Downloading setuptools-71.0.3-py3-none-any.whl.metadata (6.5 kB)
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Downloading pip-24.1.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 9.9 MB/s eta 0:00:00
Downloading setuptools-71.0.3-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 24.2 MB/s eta 0:00:00
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 6.3 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-24.1.2 setuptools-71.0.3 wheel-0.43.0
```

Then `pytest`:
```console
(...)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/tmp/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 992, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/tmp/venv/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/venv/lib/python3.8/site-packages/setuptools/_vendor/typeguard/__init__.py", line 48, in <module>
    load_plugins()
  File "/tmp/venv/lib/python3.8/site-packages/setuptools/_vendor/typeguard/_checkers.py", line 977, in load_plugins
    for ep in entry_points(group="typeguard.checker_lookup"):
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by marcinsulikowski** [comment]
It may not be actually an issue with `setuptools`. After looking a bit closed I think I know what the problem is – most likely this is because too old version of `importlib_metadata` is being installed as part of installing dependencies of the tests...

**Comment by marcinsulikowski** [comment]
Yeah, apparently `setuptools` doesn't work correctly when too old `importlib_metadata` is installed together with it. I am not sure if this is expected that I was able to create such broken installation by just calling `get-pip.py` and then `pip install -r requirements.txt` but I'll close this bug as invalid anyway.
