### ISSUE TITLE
Installation issues on Travis CI

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#345]
Originally reported by: **Anonymous**

---

Since the upload of version setuptools version 12.1 yesterday, our builds on Travis start to fail:
https://travis-ci.org/bioidiap/bob.core/jobs/50389380

Using the latest bootstrap-buildout.py, we get the following error message:

```
$ python bootstrap-buildout.py
<string>:144: DeprecationWarning: `use_setuptools` is deprecated. To enforce a specific version of setuptools, use `pkg_resources.require`.
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-12.1.zip
Extracting in /tmp/tmpRCrQju
Now working in /tmp/tmpRCrQju/setuptools-12.1
Building a Setuptools egg in /tmp/tmp7CIXgd
/tmp/tmpRCrQju/setuptools-12.1/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated. Call .resolve and .require separately.
writer = ep.load(installer=installer)
/tmp/tmp7CIXgd/setuptools-12.1-py2.6.egg
Traceback (most recent call last):
File "bootstrap-buildout.py", line 98, in <module>
ez['use_setuptools'](**setup_args)
File "<string>", line 174, in use_setuptools
File "<string>", line 129, in _do_download
File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 11, in <module>
File "build/bdist.linux-x86_64/egg/setuptools/extension.py", line 8, in <module>
File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 19, in <module>
File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 83, in <module>
AttributeError: 'module' object has no attribute '_vendor'
```

Interestingly, lines 81 and 82 of `pkg_resources/__init__.py` (the imports of the _vendor module) pass, but not the actual use of it.
Sorry for not being able to supply more information...

Could you please double-check, what might be going on?

Thank you
Manuel

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/345
