### ISSUE TITLE
With setuptools, “optional” C extension module error is fatal

### ISSUE THREAD

**Issue by dstromberg** [pypa/setuptools#1969]
Hi folks.

(There's a copy of this issue at https://stackoverflow.com/questions/59522262/with-setuptools-optional-c-extension-module-error-is-fatal)

I'm putting a little time into getting my treap module (like a dict, but always sorted by key) working with setuptools 39.0.1..

I want it to be able to compile and install the Cython version from an included .c file, or to fall back on a pure python version if that fails.

I'm currently using:

setup(
    name='treap',
    py_modules=[
        'treap',
        'py_treap',
        'nest',
        ],
    # ext_modules=cythonize("pyx_treap.pyx"),
    ext_modules=[Extension('pyx_treap', ['pyx_treap.c'], optional=True)],
    # setup_requires=[
    #     'Cython'
    # ],
    version=version,
    description='Python implementation of treaps,
)

...plus a few more options to setup that don't seem relevant.

If I run python3.6 setup.py build, I get:

running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying treap.py -> build/lib.linux-x86_64-3.6
copying py_treap.py -> build/lib.linux-x86_64-3.6
copying nest.py -> build/lib.linux-x86_64-3.6
running build_ext
building 'pyx_treap' extension
creating build/temp.linux-x86_64-3.6
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c pyx_treap.c -o
build/temp.linux-x86_64-3.6/pyx_treap.o
pyx_treap.c:4:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

So it seems like despite using Extension('pyx_treap', ['pyx_treap.c'], optional=True), the cython version is not optional.

Am I missing something? Why doesn't it just continue with the pure python modules?

I realize I could install python3.6-dev or similar to eliminate the error, but I don't want to assume the user knows that.

Thanks!

**Comment by jaraco** [comment]
The fact that you're getting `Python.h: No such file or directory` means that you don't have a suitably-configured C compiler, which would be required with or without Cython.

**Comment by jaraco** [comment]
And you said above that you want this module to be optional.

Setuptools doesn't have a mechanism to support this directly. There is a 'Features' feature of Setuptools, but that's deprecated.

One thing you can do is in the `setup.py`, test for the presence of a C compiler and fall back to a `setup()` call that doesn't include the Extension if that doesn't work.

This approach, however, also uses a discouraged behavior of altering the package structure at build time, leading to problems with binary distributions (built against one environment so can't target other environments).

You might look at what packages like `sqlalchemy` are doing these days. They may be bundling the "C speedups" as a separate, 'extra' package.

**Comment by jaraco** [comment]
Looks like Sqlalchemy uses an [environment variable switch](https://docs.sqlalchemy.org/en/13/intro.html#installing-the-c-extensions) to disable C extensions during the build.

**Comment by dstromberg** [comment]
> The fact that you're getting `Python.h: No such file or directory` means that you don't have a suitably-configured C compiler, which would be required with or without Cython.

I'm actually hoping to distribute the .c, and build from that.  If that fails, then I'd prefer for it to install just the pure python version.

So then only the system uploading to pypi should need Cython.

I may try treap[speedups].

Thanks.

**Comment by dstromberg** [comment]
IINM, the "extras" feature of setup.py is only for changing behavior if a particular pypi package is already installed?

I may have to resort to an environment variable.

**Comment by dstromberg** [comment]
What about creating two setup.py's?  One for the Cython, and one for the pure python?
