### ISSUE TITLE
[BUG] module 'distutils' has no attribute 'ccompiler'

### ISSUE THREAD

**Issue by bashkirtsevich** [pypa/setuptools#3583]
### setuptools version

65.1.0+

### Python version

3.9.2

### OS

Linux docker (debian based)

### Additional environment information

Docker official image python:3.9.2 (debian based)

### Description

After upgrading setuptools to version 65.1.0 or higher I have an error:
```
AttributeError: module 'distutils' has no attribute 'ccompiler'
```
When I trying to install [3rd party libraries](https://github.com/NVIDIA/OpenSeq2Seq/blob/master/decoders/setup.py#L65). Inside setup.py I have import like this:
```python
from setuptools import distutils ...
...
distutils.ccompiler.CCompiler.compile = parallelCCompile
```
Before 2022 Sep 09 that's work fine.

### Expected behavior

I expected:
```console
python -c 'from setuptools import distutils; print(distutils.ccompiler)'
<module 'distutils.ccompiler' from '/usr/local/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py'>
```
This code finally working on 65.0.2 version (look below to console output)

### How to Reproduce

Here is bug reproduction and test scenario (inside python:3.9.2 docker clear image):
```console
root@5fcb34f417d3:/# pip install --upgrade setuptools==65.0.2
Collecting setuptools==65.0.2
  Using cached setuptools-65.0.2-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.1.0
    Uninstalling setuptools-65.1.0:
      Successfully uninstalled setuptools-65.1.0
Successfully installed setuptools-65.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@5fcb34f417d3:/# python -c 'from setuptools import distutils; print(distutils.ccompiler)'
<module 'distutils.ccompiler' from '/usr/local/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py'>
root@5fcb34f417d3:/# pip install --upgrade setuptools==65.1.0
Collecting setuptools==65.1.0
  Using cached setuptools-65.1.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.0.2
    Uninstalling setuptools-65.0.2:
      Successfully uninstalled setuptools-65.0.2
Successfully installed setuptools-65.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@5fcb34f417d3:/# python -c 'from setuptools import distutils; print(distutils.ccompiler)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'distutils' has no attribute 'ccompiler'
root@5fcb34f417d3:/# pip install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (65.1.0)
Collecting setuptools
  Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 5.2 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.1.0
    Uninstalling setuptools-65.1.0:
      Successfully uninstalled setuptools-65.1.0
Successfully installed setuptools-65.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@5fcb34f417d3:/# python -c 'from setuptools import distutils; print(distutils.ccompiler)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'distutils' has no attribute 'ccompiler'
```

### Output

```console
python -c 'from setuptools import distutils; print(distutils.ccompiler)'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'distutils' has no attribute 'ccompiler'

```

**Comment by abravalheri** [comment]
Hi @bashkirtsevich, could you try converting your import statements to the following:

```python
import setuptools
from distutils import ccompiler  # or distutils.ccompiler
```

?

The `distutils` module is not a submodule of `setuptools`, but rather a top-level module exposed by the `setuptools` distribution. You need to import setuptools first, to ensure the latest version of `distutils` is being used instead of `distutils`.

(If in the past the statement `from setuptools import distutils...` used to work, this was due a non-reliable side effect: in Python if a module `import`s another one it will "pollute" the importer's global variable scope).

**Comment by bashkirtsevich** [comment]
Same behavior and same results.
```console
~$ docker run -it --rm python:3.9.2 bash
root@e192dc3d7ba7:/# pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 54.2.0
wheel      0.36.2
WARNING: You are using pip version 21.0.1; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@e192dc3d7ba7:/# python
Python 3.9.2 (default, Mar 31 2021, 12:13:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> from setuptools import setup, Extension, distutils
>>> distutils.ccompiler.CCompiler.compile
<function CCompiler.compile at 0x7f8ffe9139d0>
>>> quit()
root@e192dc3d7ba7:/# 
root@e192dc3d7ba7:/# 
root@e192dc3d7ba7:/# pip install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (54.2.0)
Collecting setuptools
  Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 1.3 MB/s 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 54.2.0
    Uninstalling setuptools-54.2.0:
      Successfully uninstalled setuptools-54.2.0
Successfully installed setuptools-65.3.0
WARNING: You are using pip version 21.0.1; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@e192dc3d7ba7:/# 
root@e192dc3d7ba7:/# pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 65.3.0
wheel      0.36.2
WARNING: You are using pip version 21.0.1; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@e192dc3d7ba7:/# 
root@e192dc3d7ba7:/# python
Python 3.9.2 (default, Mar 31 2021, 12:13:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> from setuptools import setup, Extension, distutils
>>> distutils.ccompiler.CCompiler.compile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'distutils' has no attribute 'ccompiler'
>>> quit()
```

**Comment by bashkirtsevich** [comment]
Well, this solution is OK.
```console
docker run -it --rm python:3.9.2 bash
root@4e240bcd4ce8:/# pip install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (54.2.0)
Collecting setuptools
  Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 1.5 MB/s 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 54.2.0
    Uninstalling setuptools-54.2.0:
      Successfully uninstalled setuptools-54.2.0
Successfully installed setuptools-65.3.0
WARNING: You are using pip version 21.0.1; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@4e240bcd4ce8:/# python
Python 3.9.2 (default, Mar 31 2021, 12:13:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> from distutils import ccompiler 
>>> ccompiler.CCompiler.compile
<function CCompiler.compile at 0x7fbb2e8fe820>
>>> 
>>> quit()
```
Thanks for you advise.
Only one solution for my problem with 3rd party (abandoned) libs -- is a fork and patch files.
